backend/api/urls.py
from django.urls import include, path
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

from api import views
from apps.courses.urls import course_router

auth_urlpatterns = [
    path("login/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("token/verify/", TokenVerifyView.as_view(), name="token_verify"),
]

urlpatterns = [
    path("healthcheck/", views.healthcheck),
    path("courses/", include(course_router.urls)),
    path("auth/", include(auth_urlpatterns)),
]

backend/apps/courses/urls.py
from django.urls import path
from rest_framework.routers import SimpleRouter

from apps.courses import views

course_router = SimpleRouter()
course_router.register(r"", views.CourseViewSet, basename="course")


urlpatterns = [
    path("<int:pk>/", views.CourseDetailView.as_view(), name="detail"),
    path("<int:pk>/delete/", views.CourseDeleteView.as_view()),
    path("<int:pk>/change/", views.CourseUpdateView.as_view()),
    path("create/", views.CourseCreateView.as_view(), name="create"),
    path("", views.CourseListView.as_view(), name="list"),
]

backend/config/urls.py
from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)

docs_urlpatterns = [
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "swagger/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    path(
        "redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"
    ),
]


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("courses/", include("apps.courses.urls")),
    path("docs/", include(docs_urlpatterns)),
    path("api/", include("api.urls")),
    path("", include("apps.registration.urls")),
]

backend/apps/courses/models.py
from ckeditor.fields import RichTextField
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.db.models import UniqueConstraint
from django.db.models.functions import Lower

from apps.users.models import User
from common.models import BaseModel


class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)

    def __str__(self) -> str:
        return f"Category: {self.name}"


class Course(BaseModel):
    class Complexity(models.IntegerChoices):
        EASY = 1, "Easy"
        MEDIUM = 2, "Medium"
        ADVANCED = 3, "Advanced"

    title = models.CharField(max_length=256)
    description = RichTextField()
    level = models.IntegerField(choices=Complexity.choices, null=True)
    language = models.CharField(max_length=32)
    category = models.ManyToManyField(Category)

    class Meta:
        constraints = [
            UniqueConstraint(
                Lower("title"), name="course_insensitive_restriction"
            )
        ]
        verbose_name = "Course"
        verbose_name_plural = "Courses"

    def __str__(self) -> str:
        return f"Course: {self.title}"


class Tag(models.Model):
    name = models.CharField(max_length=128, unique=True)

    def __str__(self) -> str:
        return f"Tag: {self.name}"


class Lesson(models.Model):
    title = models.CharField(max_length=256)
    description = models.TextField()
    tag = models.ManyToManyField(Tag, db_index=True)

    class Meta:
        constraints = [
            UniqueConstraint(
                Lower("title"), name="lesson_insensitive_restriction"
            )
        ]
        verbose_name = "Lesson"
        verbose_name_plural = "Lessons"

    def __str__(self) -> str:
        return f"Lesson {self.title}"


class LessonInCourse(models.Model):
    lesson = models.ForeignKey(Lesson, on_delete=models.PROTECT)
    course = models.ForeignKey(Course, on_delete=models.PROTECT)
    number = models.IntegerField()

    class Meta:
        unique_together = [["course", "lesson"], ["course", "number"]]

    def __str__(self):
        return f"{self.lesson} in {self.course}"


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    text = models.TextField()
    published_date = models.DateTimeField(auto_now_add=True)

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey("content_type", "object_id")

    parent = models.ForeignKey(
        "self", null=True, blank=True, on_delete=models.CASCADE
    )

    class Meta:
        ordering = ("published_date",)
        verbose_name = "Comment"
        verbose_name_plural = "Comments"

backend/apps/courses/forms.py
from django import forms

from apps.courses.models import Course


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ["title", "description", "level"]

    def __init__(self, *args, **kwargs):
        super(CourseForm, self).__init__(*args, **kwargs)
        self.empty_label = "Select"

backend/apps/courses/views.py
from django.http.request import HttpRequest
from django.http.response import HttpResponse, HttpResponseBadRequest
from django.shortcuts import get_object_or_404, redirect
from django.views import View, generic
from rest_framework import permissions, status
from rest_framework.decorators import action
from rest_framework.pagination import LimitOffsetPagination
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet

from apps.courses.forms import CourseForm
from apps.courses.models import Course, LessonInCourse
from apps.courses.serializers.courses import (
    CourseSerializer,
    LessonInCourseSerializer,
)


class CourseViewSet(ModelViewSet):
    queryset = Course.objects.all()
    serializer_class = CourseSerializer
    pagination_class = LimitOffsetPagination

    permission_classes = [permissions.IsAuthenticated]

    filterset_fields = [
        "title",
        "level",
        "category",
    ]

    search_fields = [
        "title",
    ]

    @action(detail=True, methods=["get"], url_path=r"lessons")
    def get_course_lessons(
        self, request: HttpRequest, pk: int
    ) -> HttpResponse:
        queryset = LessonInCourse.objects.filter(course=pk)
        serializer_class = LessonInCourseSerializer(queryset, many=True)
        return Response(serializer_class.data, status=status.HTTP_200_OK)


class CourseDeleteView(View):
    def post(self, request: HttpRequest, pk: int) -> HttpResponse:
        obj = get_object_or_404(Course, pk=pk)
        obj.delete()
        return redirect("list")


class CourseUpdateView(View):
    def post(self, request: HttpRequest, pk: int) -> HttpResponse:
        obj = get_object_or_404(Course, pk=pk)
        form = CourseForm(self.request.POST, instance=obj)
        if not form.is_valid():
            return HttpResponseBadRequest("Provided form's data invalid")
        form.save()
        return redirect("detail", pk=pk)


class CourseListView(generic.ListView):
    model = Course
    template_name = "courses/list.html"
    context_object_name = "courses"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = CourseForm()
        return context


class CourseDetailView(generic.DetailView):
    model = Course
    template_name = "courses/detail.html"
    context_object_name = "course"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = CourseForm(instance=context["object"])
        return context


class CourseCreateView(View):
    def post(self, request: HttpRequest) -> HttpResponse:
        form = CourseForm(self.request.POST)
        if form.is_valid():
            form.save()
        return redirect("/courses")

backend/templates/courses/detail.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% block title %}Course: {{ course.title }}{% endblock %}

{% block content %}
    <div class="card course-card">
        <div class="card-body">
            <h5 class="card-title">{{ course.title }}</h5>
            <p class="card-text">{{ course.description }}</p>
            <p class="card-text">{{ course.get_level_display }}</p>

            <div style="display: flex;">
                <button id="addCourse" style="margin-right: 4pt" type="button" class="btn btn-success">Edit</button>

                <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog"
                     aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLongTitle">Update Course</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">

                                <form action="change/" method="post">
                                    {% csrf_token %}
                                    {{ form|crispy }}
                                    <button type="submit" class="btn btn-primary">Save changes</button>
                                </form>

                            </div>
                        </div>
                    </div>
                </div>

                <form action="delete/" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </div>

        </div>
    </div>
{% endblock %}

backend/templates/courses/list.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}

    <div class="modal__container">
        <button id="addCourse" type="button" class="btn btn-primary" data-bs-toggle="modal"
            data-bs-target="#staticBackdrop">
        Add Course
        </button>
    </div>


    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog"
         aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Create Course</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                    <form action="create/" method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-primary">Save changes</button>
                    </form>

                </div>
            </div>
        </div>
    </div>

    <div class="courses__container">
        <div>
            {% for course in courses %}
                <div class="card course-card">
                    <div class="card-body">
                        <h5 class="card-title">{{ course.title }}</h5>
                        <p class="card-text">{{ course.description }}</p>
                        <a href="/courses/{{ course.pk }}" class="btn btn-primary">Apply to course</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}